### ISSUE TITLE
Error when "set on_disk=TRUE"

### ISSUE THREAD

**Issue by adamov-artem** [const-ae/transformGamPoi#1]
When I try to perform transforming on disk (as the dataset is big), I have this error in output:
> Error: The data contains negative values (Y < 0) in columns: 1,2,3,4,5,6, ...
> This is does not make sense as input data which has a support from (0 to 2^31-1).

But with the same data and on_disk=FALSE everything is fine.

**Comment by const-ae** [comment]
Hi, yes you are right that's a weird error. 
If I remember correctly the issue was that there's a bug with sparse on disk matrices. I think it was fixed in the latest bioconductor release. So, you can either try to upgrade the Bioconductor version or try to manually create a dense HDF5 backed matrix.

Unfortunately, I don't have access to a computer for the next week, so if those suggestions don't work, you'll have to be patient, so that I can properly debug the issue.

Best, Constantin

**Comment by const-ae** [comment]
Did any of the suggestions help or does the problem persist?

**Comment by adamov-artem** [comment]
Hi, yes, upgrading Bioconductor helped, thank you!

**Comment by const-ae** [comment]
Great. Let me know if you run into any other problems :)
